all:
	gcc -g -o simple_pipe simple_pipe.c
	gcc -g -o pipe_ls_wc pipe_ls_wc.c
	gcc -g -o test_prog test_prog.c
	gcc -g -o popen_test popen_test.c
	gcc bandwidth_measurement.c -o bandwidth_measurement 

